Add topaz configuration document
aserto-dev/topaz pull request #76
Opened 2023-04-20 15:56 UTC by carabasdaniel

2023-04-24 22:03 UTC, ogazitt requested changes

2023-04-24 22:03 UTC, ogazitt commented on docs/config.md
> +
perhaps add an example for configuring a remote directory (not localhost?) - including apikey, tenant id headers...

2023-04-24 22:03 UTC, ogazitt commented on docs/examples/config-private-ghcr.yaml
> +    db_path: ./pkg/testing/assets/eds-citadel.db
should this be the same as the previous example?  `${TOPAZ_DIR}/db/directory.db`

2023-04-25 13:41 UTC, gertd commented
I suggest we add an explicit paragraph on using environment variables inside the config file. 

Right now, we only show using ${TOPAZ_DIR}, but it does not get explained in terms of behavior. For example, what happens when the env variable is not existing? It will return an empty string., effectively making it a NOP.

2023-04-25 17:32 UTC, ogazitt approved these changes

2023-04-26 15:30 UTC, gertd submitted a review, later dismissed

2023-04-27 17:09 UTC, ogazitt approved these changes

2023-04-27 17:10 UTC, merged